# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc:9.3

deploy:
  stage: deploy
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install cppcheck valgrind gcovr
  script:
    - gcc -Wall -Wextra -pedantic --coverage -fprofile-arcs -ftest-coverage -g -O0 -lm main.c -o main
    - cppcheck --enable=all *.c
    - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./main
    - gcov main.c
    - mkdir coverage/
    - gcovr -r . --html --html-details -o coverage/coverage.html --print-summary
    - mv -v coverage/  public/
  artifacts:
    paths:
      - public