name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run:
        sudo apt-get install -y valgrind cppcheck
    - name: make
      run: gcc -Wall -Wextra -pedantic main.c -o main
    - name: cppcheck
      run: cppcheck --enable=all *.c
    - name: valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./main
