name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run:
        sudo apt-get install -y gcc valgrind cppcheck gcovr
    - name: make
      run: gcc -Wall -Wextra -pedantic --coverage -fprofile-arcs -ftest-coverage -g -O0 main.c -o main -lm
    - name: cppcheck
      run: cppcheck --enable=all *.c
    - name: valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./main
    - name: coverage
      run: |
        - gcov main.c
        - mkdir coverage/
        - gcovr -r . --html --html-details -o coverage/coverage.html --print-summary
